# Generated by Django 3.2.8 on 2021-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=200)),
                ('bmr', models.IntegerField()),
            ],
        ),
    ]
